volumes:
  n8n_storage:
  postgres_storage:

networks:
  n8n:  

x-n8n: &service-n8n
  image: n8nio/n8n:latest
  networks: ['n8n']
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
    - OLLAMA_HOST=${OLLAMA_HOST:-ollama:11434}
    - WEBHOOK_URL=https://n8n.yourdomain.com   #REPLACE!!!! -Webhook MUST match subdomain
  env_file:
    - path: .env
      required: true
services:
  postgres:
    image: postgres:16-alpine
    hostname: postgres
    networks: ['n8n']
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    <<: *service-n8n
    hostname: n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
  cloudflared:
    <<: *service-n8n
    hostname: cloudflared
    container_name: cloudflared
    command: 'tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}'
    image: 'cloudflare/cloudflared:latest'
    env_file:
      - path: .env
        required: true


    
